// Generated by gencpp from file beb/broadReadyRequest.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_BROADREADYREQUEST_H
#define BEB_MESSAGE_BROADREADYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beb
{
template <class ContainerAllocator>
struct broadReadyRequest_
{
  typedef broadReadyRequest_<ContainerAllocator> Type;

  broadReadyRequest_()
    : breadyask(false)  {
    }
  broadReadyRequest_(const ContainerAllocator& _alloc)
    : breadyask(false)  {
  (void)_alloc;
    }



   typedef uint8_t _breadyask_type;
  _breadyask_type breadyask;




  typedef boost::shared_ptr< ::beb::broadReadyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beb::broadReadyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct broadReadyRequest_

typedef ::beb::broadReadyRequest_<std::allocator<void> > broadReadyRequest;

typedef boost::shared_ptr< ::beb::broadReadyRequest > broadReadyRequestPtr;
typedef boost::shared_ptr< ::beb::broadReadyRequest const> broadReadyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beb::broadReadyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beb::broadReadyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'bebop_msgs': ['/home/chuggi/catkin_ws/src/bebop_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beb::broadReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beb::broadReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::broadReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::broadReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::broadReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::broadReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beb::broadReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc98afae0fe721b3d2a4fe251a0af5b2";
  }

  static const char* value(const ::beb::broadReadyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc98afae0fe721b3ULL;
  static const uint64_t static_value2 = 0xd2a4fe251a0af5b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::beb::broadReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beb/broadReadyRequest";
  }

  static const char* value(const ::beb::broadReadyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beb::broadReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool breadyask\n\
";
  }

  static const char* value(const ::beb::broadReadyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beb::broadReadyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.breadyask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct broadReadyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beb::broadReadyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beb::broadReadyRequest_<ContainerAllocator>& v)
  {
    s << indent << "breadyask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.breadyask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEB_MESSAGE_BROADREADYREQUEST_H
