// Generated by gencpp from file beb/broadReadyResponse.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_BROADREADYRESPONSE_H
#define BEB_MESSAGE_BROADREADYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beb
{
template <class ContainerAllocator>
struct broadReadyResponse_
{
  typedef broadReadyResponse_<ContainerAllocator> Type;

  broadReadyResponse_()
    : breadyres(false)  {
    }
  broadReadyResponse_(const ContainerAllocator& _alloc)
    : breadyres(false)  {
  (void)_alloc;
    }



   typedef uint8_t _breadyres_type;
  _breadyres_type breadyres;




  typedef boost::shared_ptr< ::beb::broadReadyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beb::broadReadyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct broadReadyResponse_

typedef ::beb::broadReadyResponse_<std::allocator<void> > broadReadyResponse;

typedef boost::shared_ptr< ::beb::broadReadyResponse > broadReadyResponsePtr;
typedef boost::shared_ptr< ::beb::broadReadyResponse const> broadReadyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beb::broadReadyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beb::broadReadyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'bebop_msgs': ['/home/chuggi/catkin_ws/src/bebop_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beb::broadReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beb::broadReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::broadReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::broadReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::broadReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::broadReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beb::broadReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "156b388dd2213d31d7c2fae4d877e9a7";
  }

  static const char* value(const ::beb::broadReadyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x156b388dd2213d31ULL;
  static const uint64_t static_value2 = 0xd7c2fae4d877e9a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::beb::broadReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beb/broadReadyResponse";
  }

  static const char* value(const ::beb::broadReadyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beb::broadReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool breadyres\n\
\n\
\n\
";
  }

  static const char* value(const ::beb::broadReadyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beb::broadReadyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.breadyres);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct broadReadyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beb::broadReadyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beb::broadReadyResponse_<ContainerAllocator>& v)
  {
    s << indent << "breadyres: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.breadyres);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEB_MESSAGE_BROADREADYRESPONSE_H
