// Generated by gencpp from file beb/EstimateResponse.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_ESTIMATERESPONSE_H
#define BEB_MESSAGE_ESTIMATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace beb
{
template <class ContainerAllocator>
struct EstimateResponse_
{
  typedef EstimateResponse_<ContainerAllocator> Type;

  EstimateResponse_()
    : Est()  {
    }
  EstimateResponse_(const ContainerAllocator& _alloc)
    : Est(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Est_type;
  _Est_type Est;




  typedef boost::shared_ptr< ::beb::EstimateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beb::EstimateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EstimateResponse_

typedef ::beb::EstimateResponse_<std::allocator<void> > EstimateResponse;

typedef boost::shared_ptr< ::beb::EstimateResponse > EstimateResponsePtr;
typedef boost::shared_ptr< ::beb::EstimateResponse const> EstimateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beb::EstimateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beb::EstimateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'bebop_msgs': ['/home/chuggi/catkin_ws/src/bebop_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beb::EstimateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beb::EstimateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::EstimateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::EstimateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::EstimateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::EstimateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beb::EstimateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e7571790b7810aa1510470e70dc8253";
  }

  static const char* value(const ::beb::EstimateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e7571790b7810aaULL;
  static const uint64_t static_value2 = 0x1510470e70dc8253ULL;
};

template<class ContainerAllocator>
struct DataType< ::beb::EstimateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beb/EstimateResponse";
  }

  static const char* value(const ::beb::EstimateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beb::EstimateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 Est\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::beb::EstimateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beb::EstimateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Est);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beb::EstimateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beb::EstimateResponse_<ContainerAllocator>& v)
  {
    s << indent << "Est: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Est);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEB_MESSAGE_ESTIMATERESPONSE_H
