// Generated by gencpp from file beb/randomDelay.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_RANDOMDELAY_H
#define BEB_MESSAGE_RANDOMDELAY_H

#include <ros/service_traits.h>


#include <beb/randomDelayRequest.h>
#include <beb/randomDelayResponse.h>


namespace beb
{

struct randomDelay
{

typedef randomDelayRequest Request;
typedef randomDelayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct randomDelay
} // namespace beb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beb::randomDelay > {
  static const char* value()
  {
    return "68d62eabb296c2a798f5e1a21d129e0d";
  }

  static const char* value(const ::beb::randomDelay&) { return value(); }
};

template<>
struct DataType< ::beb::randomDelay > {
  static const char* value()
  {
    return "beb/randomDelay";
  }

  static const char* value(const ::beb::randomDelay&) { return value(); }
};


// service_traits::MD5Sum< ::beb::randomDelayRequest> should match 
// service_traits::MD5Sum< ::beb::randomDelay > 
template<>
struct MD5Sum< ::beb::randomDelayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beb::randomDelay >::value();
  }
  static const char* value(const ::beb::randomDelayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beb::randomDelayRequest> should match 
// service_traits::DataType< ::beb::randomDelay > 
template<>
struct DataType< ::beb::randomDelayRequest>
{
  static const char* value()
  {
    return DataType< ::beb::randomDelay >::value();
  }
  static const char* value(const ::beb::randomDelayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beb::randomDelayResponse> should match 
// service_traits::MD5Sum< ::beb::randomDelay > 
template<>
struct MD5Sum< ::beb::randomDelayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beb::randomDelay >::value();
  }
  static const char* value(const ::beb::randomDelayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beb::randomDelayResponse> should match 
// service_traits::DataType< ::beb::randomDelay > 
template<>
struct DataType< ::beb::randomDelayResponse>
{
  static const char* value()
  {
    return DataType< ::beb::randomDelay >::value();
  }
  static const char* value(const ::beb::randomDelayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEB_MESSAGE_RANDOMDELAY_H
