// Generated by gencpp from file beb/SendDelayLogicResponse.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_SENDDELAYLOGICRESPONSE_H
#define BEB_MESSAGE_SENDDELAYLOGICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beb
{
template <class ContainerAllocator>
struct SendDelayLogicResponse_
{
  typedef SendDelayLogicResponse_<ContainerAllocator> Type;

  SendDelayLogicResponse_()
    : senddb(false)  {
    }
  SendDelayLogicResponse_(const ContainerAllocator& _alloc)
    : senddb(false)  {
  (void)_alloc;
    }



   typedef uint8_t _senddb_type;
  _senddb_type senddb;





  typedef boost::shared_ptr< ::beb::SendDelayLogicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beb::SendDelayLogicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendDelayLogicResponse_

typedef ::beb::SendDelayLogicResponse_<std::allocator<void> > SendDelayLogicResponse;

typedef boost::shared_ptr< ::beb::SendDelayLogicResponse > SendDelayLogicResponsePtr;
typedef boost::shared_ptr< ::beb::SendDelayLogicResponse const> SendDelayLogicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beb::SendDelayLogicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beb::SendDelayLogicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'bebop_msgs': ['/home/umar/catkin_ws/src/bebop_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beb::SendDelayLogicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beb::SendDelayLogicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beb::SendDelayLogicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e52faeaea82bd7603b003f2316da72c4";
  }

  static const char* value(const ::beb::SendDelayLogicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe52faeaea82bd760ULL;
  static const uint64_t static_value2 = 0x3b003f2316da72c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beb/SendDelayLogicResponse";
  }

  static const char* value(const ::beb::SendDelayLogicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool senddb\n\
\n\
";
  }

  static const char* value(const ::beb::SendDelayLogicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.senddb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendDelayLogicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beb::SendDelayLogicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beb::SendDelayLogicResponse_<ContainerAllocator>& v)
  {
    s << indent << "senddb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.senddb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEB_MESSAGE_SENDDELAYLOGICRESPONSE_H
