// Generated by gencpp from file beb/TrReady.msg
// DO NOT EDIT!


#ifndef BEB_MESSAGE_TRREADY_H
#define BEB_MESSAGE_TRREADY_H

#include <ros/service_traits.h>


#include <beb/TrReadyRequest.h>
#include <beb/TrReadyResponse.h>


namespace beb
{

struct TrReady
{

typedef TrReadyRequest Request;
typedef TrReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrReady
} // namespace beb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beb::TrReady > {
  static const char* value()
  {
    return "48dfce180ae15a999c8da093ded5649e";
  }

  static const char* value(const ::beb::TrReady&) { return value(); }
};

template<>
struct DataType< ::beb::TrReady > {
  static const char* value()
  {
    return "beb/TrReady";
  }

  static const char* value(const ::beb::TrReady&) { return value(); }
};


// service_traits::MD5Sum< ::beb::TrReadyRequest> should match 
// service_traits::MD5Sum< ::beb::TrReady > 
template<>
struct MD5Sum< ::beb::TrReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beb::TrReady >::value();
  }
  static const char* value(const ::beb::TrReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beb::TrReadyRequest> should match 
// service_traits::DataType< ::beb::TrReady > 
template<>
struct DataType< ::beb::TrReadyRequest>
{
  static const char* value()
  {
    return DataType< ::beb::TrReady >::value();
  }
  static const char* value(const ::beb::TrReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beb::TrReadyResponse> should match 
// service_traits::MD5Sum< ::beb::TrReady > 
template<>
struct MD5Sum< ::beb::TrReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beb::TrReady >::value();
  }
  static const char* value(const ::beb::TrReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beb::TrReadyResponse> should match 
// service_traits::DataType< ::beb::TrReady > 
template<>
struct DataType< ::beb::TrReadyResponse>
{
  static const char* value()
  {
    return DataType< ::beb::TrReady >::value();
  }
  static const char* value(const ::beb::TrReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEB_MESSAGE_TRREADY_H
