// Generated by gencpp from file et_circumnavigation/AddAgent.msg
// DO NOT EDIT!


#ifndef ET_CIRCUMNAVIGATION_MESSAGE_ADDAGENT_H
#define ET_CIRCUMNAVIGATION_MESSAGE_ADDAGENT_H

#include <ros/service_traits.h>


#include <et_circumnavigation/AddAgentRequest.h>
#include <et_circumnavigation/AddAgentResponse.h>


namespace et_circumnavigation
{

struct AddAgent
{

typedef AddAgentRequest Request;
typedef AddAgentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddAgent
} // namespace et_circumnavigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::et_circumnavigation::AddAgent > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::et_circumnavigation::AddAgent&) { return value(); }
};

template<>
struct DataType< ::et_circumnavigation::AddAgent > {
  static const char* value()
  {
    return "et_circumnavigation/AddAgent";
  }

  static const char* value(const ::et_circumnavigation::AddAgent&) { return value(); }
};


// service_traits::MD5Sum< ::et_circumnavigation::AddAgentRequest> should match 
// service_traits::MD5Sum< ::et_circumnavigation::AddAgent > 
template<>
struct MD5Sum< ::et_circumnavigation::AddAgentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::AddAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::AddAgentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::AddAgentRequest> should match 
// service_traits::DataType< ::et_circumnavigation::AddAgent > 
template<>
struct DataType< ::et_circumnavigation::AddAgentRequest>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::AddAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::AddAgentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::et_circumnavigation::AddAgentResponse> should match 
// service_traits::MD5Sum< ::et_circumnavigation::AddAgent > 
template<>
struct MD5Sum< ::et_circumnavigation::AddAgentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::AddAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::AddAgentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::AddAgentResponse> should match 
// service_traits::DataType< ::et_circumnavigation::AddAgent > 
template<>
struct DataType< ::et_circumnavigation::AddAgentResponse>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::AddAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::AddAgentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ET_CIRCUMNAVIGATION_MESSAGE_ADDAGENT_H
