// Generated by gencpp from file et_circumnavigation/RemoveAgent.msg
// DO NOT EDIT!


#ifndef ET_CIRCUMNAVIGATION_MESSAGE_REMOVEAGENT_H
#define ET_CIRCUMNAVIGATION_MESSAGE_REMOVEAGENT_H

#include <ros/service_traits.h>


#include <et_circumnavigation/RemoveAgentRequest.h>
#include <et_circumnavigation/RemoveAgentResponse.h>


namespace et_circumnavigation
{

struct RemoveAgent
{

typedef RemoveAgentRequest Request;
typedef RemoveAgentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveAgent
} // namespace et_circumnavigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::et_circumnavigation::RemoveAgent > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::et_circumnavigation::RemoveAgent&) { return value(); }
};

template<>
struct DataType< ::et_circumnavigation::RemoveAgent > {
  static const char* value()
  {
    return "et_circumnavigation/RemoveAgent";
  }

  static const char* value(const ::et_circumnavigation::RemoveAgent&) { return value(); }
};


// service_traits::MD5Sum< ::et_circumnavigation::RemoveAgentRequest> should match 
// service_traits::MD5Sum< ::et_circumnavigation::RemoveAgent > 
template<>
struct MD5Sum< ::et_circumnavigation::RemoveAgentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::RemoveAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::RemoveAgentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::RemoveAgentRequest> should match 
// service_traits::DataType< ::et_circumnavigation::RemoveAgent > 
template<>
struct DataType< ::et_circumnavigation::RemoveAgentRequest>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::RemoveAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::RemoveAgentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::et_circumnavigation::RemoveAgentResponse> should match 
// service_traits::MD5Sum< ::et_circumnavigation::RemoveAgent > 
template<>
struct MD5Sum< ::et_circumnavigation::RemoveAgentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::RemoveAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::RemoveAgentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::RemoveAgentResponse> should match 
// service_traits::DataType< ::et_circumnavigation::RemoveAgent > 
template<>
struct DataType< ::et_circumnavigation::RemoveAgentResponse>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::RemoveAgent >::value();
  }
  static const char* value(const ::et_circumnavigation::RemoveAgentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ET_CIRCUMNAVIGATION_MESSAGE_REMOVEAGENT_H
