// Generated by gencpp from file et_circumnavigation/Topology.msg
// DO NOT EDIT!


#ifndef ET_CIRCUMNAVIGATION_MESSAGE_TOPOLOGY_H
#define ET_CIRCUMNAVIGATION_MESSAGE_TOPOLOGY_H

#include <ros/service_traits.h>


#include <et_circumnavigation/TopologyRequest.h>
#include <et_circumnavigation/TopologyResponse.h>


namespace et_circumnavigation
{

struct Topology
{

typedef TopologyRequest Request;
typedef TopologyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Topology
} // namespace et_circumnavigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::et_circumnavigation::Topology > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::et_circumnavigation::Topology&) { return value(); }
};

template<>
struct DataType< ::et_circumnavigation::Topology > {
  static const char* value()
  {
    return "et_circumnavigation/Topology";
  }

  static const char* value(const ::et_circumnavigation::Topology&) { return value(); }
};


// service_traits::MD5Sum< ::et_circumnavigation::TopologyRequest> should match 
// service_traits::MD5Sum< ::et_circumnavigation::Topology > 
template<>
struct MD5Sum< ::et_circumnavigation::TopologyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::Topology >::value();
  }
  static const char* value(const ::et_circumnavigation::TopologyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::TopologyRequest> should match 
// service_traits::DataType< ::et_circumnavigation::Topology > 
template<>
struct DataType< ::et_circumnavigation::TopologyRequest>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::Topology >::value();
  }
  static const char* value(const ::et_circumnavigation::TopologyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::et_circumnavigation::TopologyResponse> should match 
// service_traits::MD5Sum< ::et_circumnavigation::Topology > 
template<>
struct MD5Sum< ::et_circumnavigation::TopologyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::et_circumnavigation::Topology >::value();
  }
  static const char* value(const ::et_circumnavigation::TopologyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::et_circumnavigation::TopologyResponse> should match 
// service_traits::DataType< ::et_circumnavigation::Topology > 
template<>
struct DataType< ::et_circumnavigation::TopologyResponse>
{
  static const char* value()
  {
    return DataType< ::et_circumnavigation::Topology >::value();
  }
  static const char* value(const ::et_circumnavigation::TopologyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ET_CIRCUMNAVIGATION_MESSAGE_TOPOLOGY_H
