(cl:defpackage et_circumnavigation-srv
  (:use )
  (:export
   "CIRCUM"
   "<CIRCUM-REQUEST>"
   "CIRCUM-REQUEST"
   "<CIRCUM-RESPONSE>"
   "CIRCUM-RESPONSE"
   "ADDAGENT"
   "<ADDAGENT-REQUEST>"
   "ADDAGENT-REQUEST"
   "<ADDAGENT-RESPONSE>"
   "ADDAGENT-RESPONSE"
   "TOPOLOGY"
   "<TOPOLOGY-REQUEST>"
   "TOPOLOGY-REQUEST"
   "<TOPOLOGY-RESPONSE>"
   "TOPOLOGY-RESPONSE"
   "REMOVEAGENT"
   "<REMOVEAGENT-REQUEST>"
   "REMOVEAGENT-REQUEST"
   "<REMOVEAGENT-RESPONSE>"
   "REMOVEAGENT-RESPONSE"
  ))

